events {}

http {

    upstream frontend {
        server frontend_1:80;
        server frontend_2:80;
    }

    upstream backend_usuarios {
        server backend-usuarios_1:8081;
        server backend-usuarios_2:8081;
    }

    upstream backend_productos {
        server backend-productos_1:8082;
        server backend-productos_2:8082;
    }

    upstream backend_reportes {
        server backend-reportes_1:8083;
        server backend-reportes_2:8083;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
        }

        location /api/usuarios {
            proxy_pass http://backend_usuarios;
            proxy_set_header Host "backend-usuarios";
        }

        location /api/productos {
            proxy_pass http://backend_productos;
            proxy_set_header Host "backend-productos";
        }

        location /api/ventas {
            proxy_pass http://backend_reportes;
            proxy_set_header Host "backend-reportes";
        }
    }
}